#pragma once

#include "NativeGameplayTags.h"

namespace BOGameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Attacker);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Team_Defender);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Round_Phase_WaitingForPlayers);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Round_Phase_Warmup);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Round_Phase_Buy);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Round_Phase_Live);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Round_Phase_BombPlanted);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Round_Phase_RoundEnding);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Round_Phase_MatchEnding);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Bullet);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Damage_Explosion);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Rifle);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Pistol);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Melee);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gadget_Smoke);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gadget_Flash);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gadget_Explosive);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gadget_Decoy);

	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Flashed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Suppressed);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Interacting);
}

